/* --- Generated the 6/4/2019 at 1:55 --- */
/* --- heptagon compiler, version 1.05.00 (compiled wed. mar. 13 20:25:55 CET 2019) --- */
/* --- Command line: /home/labcontrol/.opam/default/bin/heptc -target c duas_tarefas_concorrentes_controller.ept --- */

#ifndef DUAS_TAREFAS_CONCORRENTES_CONTROLLER_H
#define DUAS_TAREFAS_CONCORRENTES_CONTROLLER_H

#include "duas_tarefas_concorrentes_controller_types.h"
typedef struct Duas_tarefas_concorrentes_controller__duas_tarefas_concorrentes_controller_duas_tarefas_concorrentes_c2_out {
  int duas_tarefas_concorrentes_c2;
} Duas_tarefas_concorrentes_controller__duas_tarefas_concorrentes_controller_duas_tarefas_concorrentes_c2_out;

void Duas_tarefas_concorrentes_controller__duas_tarefas_concorrentes_controller_duas_tarefas_concorrentes_c2_step(
int duas_tarefas_concorrentes_r1, int duas_tarefas_concorrentes_e1,
int duas_tarefas_concorrentes_r2, int duas_tarefas_concorrentes_e2,
int duas_tarefas_concorrentes_v_57, int duas_tarefas_concorrentes_v_56,
int duas_tarefas_concorrentes_pnr_1, int duas_tarefas_concorrentes_v_41,
int duas_tarefas_concorrentes_v_40, int duas_tarefas_concorrentes_pnr,
int p_duas_tarefas_concorrentes_c2, int p_duas_tarefas_concorrentes_c1,
int duas_tarefas_concorrentes_c1,
Duas_tarefas_concorrentes_controller__duas_tarefas_concorrentes_controller_duas_tarefas_concorrentes_c2_out* _out);

typedef struct Duas_tarefas_concorrentes_controller__duas_tarefas_concorrentes_controller_duas_tarefas_concorrentes_c1_out {
  int duas_tarefas_concorrentes_c1;
} Duas_tarefas_concorrentes_controller__duas_tarefas_concorrentes_controller_duas_tarefas_concorrentes_c1_out;

void Duas_tarefas_concorrentes_controller__duas_tarefas_concorrentes_controller_duas_tarefas_concorrentes_c1_step(
int duas_tarefas_concorrentes_r1, int duas_tarefas_concorrentes_e1,
int duas_tarefas_concorrentes_r2, int duas_tarefas_concorrentes_e2,
int duas_tarefas_concorrentes_v_57, int duas_tarefas_concorrentes_v_56,
int duas_tarefas_concorrentes_pnr_1, int duas_tarefas_concorrentes_v_41,
int duas_tarefas_concorrentes_v_40, int duas_tarefas_concorrentes_pnr,
int p_duas_tarefas_concorrentes_c2, int p_duas_tarefas_concorrentes_c1,
Duas_tarefas_concorrentes_controller__duas_tarefas_concorrentes_controller_duas_tarefas_concorrentes_c1_out* _out);

typedef struct Duas_tarefas_concorrentes_controller__duas_tarefas_concorrentes_controller_out {
  int duas_tarefas_concorrentes_c2;
  int duas_tarefas_concorrentes_c1;
} Duas_tarefas_concorrentes_controller__duas_tarefas_concorrentes_controller_out;

void Duas_tarefas_concorrentes_controller__duas_tarefas_concorrentes_controller_step(
int duas_tarefas_concorrentes_r1, int duas_tarefas_concorrentes_e1,
int duas_tarefas_concorrentes_r2, int duas_tarefas_concorrentes_e2,
int duas_tarefas_concorrentes_v_57, int duas_tarefas_concorrentes_v_56,
int duas_tarefas_concorrentes_pnr_1, int duas_tarefas_concorrentes_v_41,
int duas_tarefas_concorrentes_v_40, int duas_tarefas_concorrentes_pnr,
int p_duas_tarefas_concorrentes_c2, int p_duas_tarefas_concorrentes_c1,
Duas_tarefas_concorrentes_controller__duas_tarefas_concorrentes_controller_out* _out);

#endif // DUAS_TAREFAS_CONCORRENTES_CONTROLLER_H
